# Site
name: "Warren Crasta's Blog"
description: "Blog"
meta_description: "Warren Crasta's Blog"

# Authors
authors:
  warren:
    name: Warren Crasta
    display_name: Warren Crasta
    avatar: https://i.imgur.com/TSbHeyQ.png
    email: warrencrasta@gmail.com
    twitter: https://twitter.com/warrencrasta
    description: "Software Engineer. Recent grad from UT-Austin."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge